"""empty message

Revision ID: b84a1b9acd06
Revises: 1ac7bc5f82f6
Create Date: 2023-10-20 15:44:55.246960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84a1b9acd06'
down_revision = '1ac7bc5f82f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
